	DATA_SEG SEGMENT
	DATA_SEG ENDS

	STACK_SEG SEGMENT STACK
		 DB	  200  DUP(0)
	STACK_SEG ENDS

	CODE_SEG SEGMENT
		ASSUME CS: CODE_SEG DS: DATA_SEG SS: STACK_SEG
	START:	 
		MOV AX, DATA_SEG
		MOV DS, AX
		
	CODE_SEG ENDS
		END START
