#!/usr/bin/expect
# Created by Robert Wu - QD x5258
# To see detail log, change log_user to 1
log_user 1

set spa [ lindex $argv 0 ]
set timeout -1
if { $spa == "" } {
	send "Usage: inst_spa spa_name \n"
	exit
}

#spawn -noecho subshl
spawn -noecho ssh ainet@vm10
expect "password:"
send "ainet1\n"
expect "bj*>"
send "subshl\n"
expect "<"
send "install:config,spa=$spa\n"
expect {
	"INSTALLATION COMPLETE" {
		puts "$argv0 install:config success for $spa"
		}	
	"FAILED*EXISTS)" {
		puts "$argv0 INFO: install:config - $spa already exists, will continue the install"
		}
	"INSTALL*FAILED" {
		puts "$argv0 ERR: install:config failed for $spa"
		send "quit\n"
		send "exit\n"
		exit 1
		}
}
sleep 1
expect "<"
send "install:proc,spa=$spa\n"
expect {
	"SPA*SUCCEEDED" {
		puts "$argv0 install:proc success for $spa"
		}	
	"SPA NAME ALREADY EXISTS" {
		puts "$argv0 INFO: install:proc - $spa already exists, will continue the install"
		}
	"INSTALL*FAILED" {
		puts "$argv0 ERR: install:proc fail for $spa"
		expect "<"
		send "quit\n"
		send "exit\n"
		exit 1
		}
}
expect "<"
sleep 2
send "rst:spa=$spa\n"
expect {
	"RST*SUCCESSFULLY" {
		puts "$argv0 rst:spa success for $spa -- installation DONE"
		}
	"SPA ALREADY IN SERVICE" {
		puts "$argv0 INFO: rst:spa, $spa ALREADY IN SERVICE"
		}
	"RST*FAILED" {
		puts "$argv0 ERR: rst:spa fail for $spa"
		expect "<"
		send "quit\n"
		send "exit\n"
		exit 1
		}
}
expect "<"
send "quit\n"
send "exit\n"
exit 0
