#!/usr/bin/expect
# Created by Robert Wu - QD x5258
# To see detail log, change log_user to 1
log_user 1

set spa [ lindex $argv 0 ]
set timeout -1
if { $spa == "" } {
	send "Usage: inst_spa spa_name \n"
	exit
}

#spawn -noecho subshl
spawn -noecho ssh ainet@vm10
expect "password:"
send "ainet1\n"
expect "bj*>"
send "subshl\n"
expect "<"
send "install:config,spa=$spa\n"
expect {
        "INSTALLATION COMPLETE" {
                puts "$argv0 install:config success for $spa"
                }
        "FAILED*EXISTS)" {
                puts "$argv0 INFO: install:config - $spa already exists, will continue the install"
                }
	"INSTALL*FAILED" {
		puts "$argv0 ERR: install:config failed for $spa"
		send "quit\n"
		send "exit\n"
		exit 1
		}
}
sleep 1
expect "<"
send "quit\n"
send "exit\n"
exit 0

