#!/usr/bin/expect
# Created by Robert Wu - QD x5258
# To see detail log, change log_user to 1
log_user 1

spawn -noecho ssh ainet@vm10
expect "password:"
send "ainet1\n"
expect "vm*"
send "su -\n"
expect "word:"
send "r00t\n"
interact
